### ISSUE TITLE
License Q.

### ISSUE THREAD

**Issue by ModMorph** [facebookresearch/convit#1]
CC-BY-NC 4.0? FB getting into the B2B AI hosted services business? Or patent cross licensing /legal weirdness to protect against? Anyhow, look forward to reviewing your paper after I get through my transformer paper backlog. Just curious, since most FAIR projects seemed like BSD, MIT, or Apache 2.0 if I recall correctly. thx. cheers.

**Comment by sdascoli** [comment]
Hi there,
The license has just been updated to Apache 2.0.
Best wishes !
