### ISSUE TITLE
Question on equation (5)

### ISSUE THREAD

**Issue by Charleshhy** [facebookresearch/convit#12]
Hi,

Thanks for your great work and repo! I just have a quick question on equation (5) of your paper.

In your paper and code:
![image](https://user-images.githubusercontent.com/39027479/127414981-f32c9c81-72cf-4305-871f-fb0be944f709.png)

It seems you have forced the value projection matrix to be an identity matrix all the time to make sure quadratic encoding works. However, in paper [On the Relationship between Self-Attention and Convolutional Layers](https://arxiv.org/abs/1911.03584), the quadratic encoding equation is defined differently as:
![image](https://user-images.githubusercontent.com/39027479/127415141-0f919526-e136-4dcd-b383-682470f34ff6.png),
that the \hat{key} projection matrix that calculates relative position embedding:
![image](https://user-images.githubusercontent.com/39027479/127415203-795576b7-4b8b-48aa-99a8-622583313cbd.png)
is kept as an identity matrix, which is different to your implementation since you have kept both \hat{key} and value matrix as identity matrices.

Can you kindly let me know whether I have misunderstood anything?

Kind regards,
Haoyu

**Comment by sdascoli** [comment]
Dear Haoyu, 
This is a very good point, thank you for bringing it up. 
Note that our parametrization does not use the matrix \hat W_key, which is equivalent to saying that we fix it to the identity.
Our parametrization does indeed initialize the value matrix to the identity (but does no enforce it to stay equal to the identity). Indeed, this initialization is not required to obtain a quadratic encoding; the reason we used it was to enable the ConViT to represent a pretrained convolution, as in the subsequent [Transformed CNN](https://arxiv.org/abs/2106.05795) paper. However it is not useful in itself, and we will remove it in a subsequent update (although it is probably not harmful).
Many thanks !

**Comment by Charleshhy** [comment]
Dear Stéphane,

Thanks a lot for the clarification! I will close this issue then!

Cheers,
Haoyu
