### ISSUE TITLE
Multi-GPUs training

### ISSUE THREAD

**Issue by Administor123** [facebookresearch/convit#13]
Hello, I have some questions about Multi-GPUs training as follows:
I don't know how to add parameters when I use function as
`CUDA_VISIBLE_DEVICES=0,1,2,3,4,5,6,7 python -m torch.distributed.launch --nproc_per_node=8 main.py`
I want to add
 `kinetics RGB --arch tea50 --num_segments 8 --gpus 0 1 2 3 4 5 6 7 --gd 20 --lr 0.0009 --lr_steps 20 40 --epochs 200 --batch-size 16 -j 16 --dropout 0.5 --consensus_type=avg --eval-freq=1 --print-freq=200 --experiment_name=TEA --shift --shift_div=8 --resume 0 --shift_place=blockres
`
Can you help me?  I'm overwhelmed with gratitude

**Comment by sdascoli** [comment]
Hi, you should be able to put all your arguments just after the ```main.py```, just as you would do usually !
Best wishes

**Comment by Administor123** [comment]
My command is `CUDA_VISIBLE_DEVICES=0,1,2,3,4,5,6,7 python -m torch.distributed.launch --nproc_per_node=8 main.py kinetics RGB --arch tea50 --num_segments 8 --gpus 0 1 2 3 4 5 6 7 --gd 20 --lr 0.0009 --lr_steps 20 40 --epochs 200 --batch-size 16 -j 16 --dropout 0.5 --consensus_type=avg --eval-freq=1 --print-freq=200 --experiment_name=TEA --shift --shift_div=8 --resume 0 --shift_place=blockres`
but it's wrong.The wrong information was so long ,so I intercepted part of it
`usage: main.py [-h] [--train_list TRAIN_LIST] [--val_list VAL_LIST]
               [--store_name STORE_NAME] [--arch ARCH]
               [--num_segments NUM_SEGMENTS] [--consensus_type CONSENSUS_TYPE]
               [--k K] [--dropout DO] [--loss_type {nll}]
               [--img_feature_dim IMG_FEATURE_DIM] [--suffix SUFFIX]
               [--pretrain PRETRAIN] [--tune_from TUNE_FROM] [--epochs N]
               [-b N] [--lr LR] [--lr_type LRtype]
               [--lr_steps LRSteps [LRSteps ...]] [--momentum M]
               [--weight-decay W] [--clip-gradient W] [--no_partialbn]
               [--print-freq N] [--eval-freq N] [-j N] [--resume PATH] [-e]
               [--snapshot_pref SNAPSHOT_PREF] [--start-epoch N]
               [--gpus GPUS [GPUS ...]] [--flow_prefix FLOW_PREFIX]
               [--root_log ROOT_LOG] [--root_model ROOT_MODEL]
               [--experiment_name EXPERIMENT_NAME] [--shift]
               [--shift_div SHIFT_DIV] [--shift_place SHIFT_PLACE]
               [--dense_sample]
               dataset {RGB,Flow}
main.py: error: unrecognized arguments: --local_rank=7
Traceback (most recent call last):
  File "/home/syq/opt/anaconda2/envsnb/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/home/syq/opt/anaconda2/envsnb/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/syq/opt/anaconda2/envsnb/python3.6/site-packages/torch/distributed/launch.py", line 253, in <module>
    main()
  File "/home/syq/opt/anaconda2/envsnb/python3.6/site-packages/torch/distributed/launch.py", line 249, in main
    cmd=cmd)
subprocess.CalledProcessError: Command '['/home/syq/opt/anaconda2/envsn/bin/python', '-u', 'main.py', '--local_rank=7', 'kinetics', 'RGB', '--arch', 'tea50', '--num_segments', '8', '--gpus', '0', '1', '2', '3', '4', '5', '6', '7', '--gd', '20', '--lr', '0.0009', '--lr_steps', '20', '40', '--epochs', '200', '--batch-size', '16', '-j', '16', '--dropout', '0.5', '--consensus_type=avg', '--eval-freq=1', '--print-freq=200', '--experiment_name=TEA', '--shift', '--shift_div=8', '--resume', '0', '--shift_place=blockres']' returned non-zero exit status 2.`
