### ISSUE TITLE
Import error when running in colab

### ISSUE THREAD

**Issue by NouranFadlallah** [facebookresearch/convit#14]
Hello,
I'm trying to run the evaluation or training codes given on colab:
`!python /content/convit/main.py --eval --model convit_tiny --pretrained --data-path /content/drive/MyDrive/convitry/
`
and:
`!python -m torch.distributed.launch --use_env /content/convit/main.py --model convit_tiny --batch-size 256 --data-path /content/drive/MyDrive/convitry/
`
and I keep getting this error:

ImportError: cannot import name 'container_abcs' from 'torch._six' (/usr/local/lib/python3.7/dist-packages/torch/_six.py)

Can you help? Also any notes on running the code on colab?

**Comment by Tylersuard** [comment]
!pip install --upgrade timm

**Comment by NouranFadlallah** [comment]
Worked! thanks
