### ISSUE TITLE
How to train on custom data using Colab?

### ISSUE THREAD

**Issue by Tylersuard** [facebookresearch/convit#15]
I am getting this error:
Namespace(aa='rand-m9-mstd0.5-inc1', batch_size=64, clip_grad=None, color_jitter=0.4, cooldown_epochs=10, cutmix=1.0, cutmix_minmax=None, data_path='/content/stonks', data_set='IMNET', decay_epochs=30, decay_rate=0.1, device='cuda', dist_url='env://', distributed=False, drop=0.0, drop_block=None, drop_path=0.1, embed_dim=48, epochs=300, eval=False, inat_category='name', input_size=224, local_up_to_layer=10, locality_strength=1.0, lr=0.0005, lr_noise=None, lr_noise_pct=0.67, lr_noise_std=1.0, min_lr=1e-05, mixup=0.8, mixup_mode='batch', mixup_prob=1.0, mixup_switch_prob=0.5, model='convit_tiny', model_ema=False, model_ema_decay=0.99996, model_ema_force_cpu=False, momentum=0.9, nb_classes=None, num_workers=10, opt='adamw', opt_betas=None, opt_eps=1e-08, output_dir='', patience_epochs=10, pin_mem=True, pretrained=False, recount=1, remode='pixel', repeated_aug=True, reprob=0.25, resplit=False, resume='', sampling_ratio=1.0, save_every=None, sched='cosine', seed=0, smoothing=0.1, start_epoch=0, train_interpolation='bicubic', warmup_epochs=5, warmup_lr=1e-06, weight_decay=0.05, world_size=1)
Traceback (most recent call last):
  File "/content/convit/main.py", line 383, in <module>
    main(args)
  File "/content/convit/main.py", line 194, in main
    dataset_train, args.nb_classes = build_dataset(is_train=True, args=args)
  File "/content/convit/datasets.py", line 148, in build_dataset
    sampling_ratio= (args.sampling_ratio if is_train else 1.), nb_classes=args.nb_classes)
  File "/content/convit/datasets.py", line 130, in __init__
    is_valid_file=is_valid_file, **kwargs)
  File "/content/convit/datasets.py", line 107, in __init__
    classes, class_to_idx = self._find_classes(self.root)
AttributeError: 'ImageNetDataset' object has no attribute '_find_classes'

**Comment by NouranFadlallah** [comment]
I removed the _ before find_classes in datasets.py .. this way you're using find_classes() func from torchvision.datasets.datasetfolder

**Comment by Tylersuard** [comment]
Thank you!

**Comment by NouranFadlallah** [comment]
Any good results on custom data? mine are terrible so far

**Comment by Tylersuard** [comment]
@NouranFadlallah Mine is still training.  How are you testing yours?
