### ISSUE TITLE
Multilabel classification for training 

### ISSUE THREAD

**Issue by abhigoku10** [facebookresearch/convit#17]
@likethesky @sdascoli  i want to train convit for multi label classification whose input image size is 256 x128 with label as vectors can i do to so , if so what changes i have to make in training pipeline 
Thanks in advance

**Comment by sdascoli** [comment]
Hi, one would need to interpolate the positional embeddings - see https://github.com/rwightman/pytorch-image-models/blob/master/timm/models/vision_transformer.py#L481.
