### ISSUE TITLE
 CC-BY-NC 4.0 License 

### ISSUE THREAD

**Issue by amaarora** [facebookresearch/convit#3]
Dear researchers hope you're well and thanks for your wonderful work on [ConViT](https://arxiv.org/abs/2103.10697). I quite enjoyed reading the paper and wasn't aware that self-attention could also express a convolutional layer [[1](https://arxiv.org/abs/1911.03584)]. 

Would love to get this model as part of TIMM, but as you can see in the discussion [here](https://github.com/rwightman/pytorch-image-models/discussions/635), Ross tells me we need to wait for an unrestrictive license. 

Just wondering if that's something in the works? Is there some time in the near future that we're going to move towards an Apache license? Why do we have a non-commercial license here, please?

**Comment by sdascoli** [comment]
Dear Aman, 
Thank you so much for you for your positive feedback.
The license has just been updated to Apache 2.0, so you should be good to go.
Best,
Stéphane
