### ISSUE TITLE
Multi-Gpu training

### ISSUE THREAD

**Issue by SZUHvern** [facebookresearch/convit#8]
Hi! Thank you for sharing the code
I have some questions about how to train with multi GPU.
When I used the original code, it can just run on only one GPU(I found that 'DistributedDataParallel' doesn't work ).
After that, I wrote that:

    # if args.distributed:
    #     model = torch.nn.parallel.DistributedDataParallel(model, device_ids='0,1')
    #     model_without_ddp = model.module

    device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
    model.to(device)
    model = DataParallel(model)
 
But suffer from this message:
RuntimeError: Expected tensor for 'out' to have the same device as tensor for argument #3 'mat2'; but device 0 does not equal 1 (while checking arguments for addmm)

Could you help me to solve this problem?
Also, what is the meaning of '--world_size' which default is setting to be '1'?

Thanks!

**Comment by sdascoli** [comment]
Hi, did you look into using ```run_with_submitit.py```or did you try the command
```python -m torch.distributed.launch --nproc_per_node=4 --use_env main.py --model convit_tiny --batch-size 256 --data-path /path/to/imagenet```?
The parallelisation code is simply imported from the [DeiT](https://github.com/facebookresearch/deit) repository.
World size corresponds to the total number of GPUs used for the run.
